baseURL = "https://chrishorner.codes"
languageCode = "en-au"
title = "Chris Horner"
pygmentsUseClasses = true
pygmentsCodefences = true
disableKinds = ["taxonomy"]
[markup.goldmark.renderer]
unsafe= true
[params.author]
	name = "Chris Horner"
	email = "chris [at] horner [dot] chat"
